# Generated by Django 4.2.1 on 2023-05-16 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Accounts", "0002_alter_person_specialization"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="allergies",
            name="Medical_Form",
        ),
        migrations.AddField(
            model_name="medical_form",
            name="Allergies",
            field=models.ManyToManyField(to="Accounts.allergies"),
        ),
    ]
