# Generated by Django 4.2.1 on 2023-05-16 21:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("Accounts", "0003_remove_allergies_medical_form_medical_form_allergies"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Vaccine",
        ),
    ]
