# Generated by Django 4.2.1 on 2023-05-16 21:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("Ticket", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="ticket",
            name="Nurses",
            field=models.ManyToManyField(
                related_name="Nurses", to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name="ticket",
            name="Patient",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="Patients",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
